export const {
    PORT = 3000,
    DB_NAME = "pruebas",
    DB_USER = "root",
    DB_PASSWORD = "admin",
    DB_HOST = "localhost",
    DB_PORT = "5432",
    JWT_SECRET = "DEFAULT_SECRET",
    REFRESH_TOKEN = "DEFAULT_REFRESH_SECRET",
    SALT_ROUNDS = "5"
} = process.env;
